from django.core.management.base import BaseCommand

IT_DARSLAR = [
    (1,  "Kursga kirish + Startap tafakkuri + Ish tizimi"),
    (2,  "Kompyuter arxitekturasi: CPU, RAM, HDD/SSD"),
    (3,  "Operatsion tizimlar: Windows, Linux, macOS"),
    (4,  "Internet va tarmoqlar: IP, DNS, HTTP, HTTPS"),
    (5,  "Dasturlash asoslari: Python bilan tanishuv"),
    (6,  "Ma'lumotlar turlari, o'zgaruvchilar, shartlar"),
    (7,  "Tsikllar, funksiyalar, modullar"),
    (8,  "Fayl bilan ishlash, kutubxonalar"),
    (9,  "OOP: Klasslar, obyektlar, meros"),
    (10, "Ma'lumotlar bazasi: SQL asoslari"),
    (11, "SQLite va Python bilan DB ishlash"),
    (12, "Web asoslari: HTML, CSS, JavaScript kirish"),
    (13, "API nima? REST API bilan ishlash"),
    (14, "Git va GitHub: versiya boshqaruvi"),
    (15, "Linux terminal buyruqlari va bash skriptlar"),
    (16, "Kiberxavfsizlik asoslari: shifrlash, xujumlar"),
    (17, "Bulut texnologiyalari: AWS, GCP, Azure"),
    (18, "Docker va konteynerlashtirish"),
    (19, "Loyiha boshqaruvi: Agile, Scrum, Trello"),
    (20, "Prezentatsiya va kommunikatsiya ko'nikmalari"),
    (21, "Startap g'oyasi: BMC (Business Model Canvas)"),
    (22, "MVP yaratish va testlash"),
    (23, "Pitch deck tayyorlash va taqdimot"),
    (24, "FINAL — Portfolio + MVP + Startap himoya"),
]

AI_DARSLAR = [
    (1,  "AI umuman nima? Tarix, turlari, hozirgi holat"),
    (2,  "ChatGPT va prompt engineering asoslari"),
    (3,  "Prompt muhandisligi: advanced texnikalar (CoT, Few-shot, Role)"),
    (4,  "AI vositalar: Midjourney, DALL·E, Runway, Sora"),
    (5,  "AI yordamida biznes avtomatlashtirish: Zapier, Make.com"),
    (6,  "AI agentlar: AutoGPT, LangChain, CrewAI"),
    (7,  "Ma'lumot tahlili uchun AI: ChatGPT + Excel/Sheets"),
    (8,  "AI bilan kontent yaratish: blog, video, SMM"),
    (9,  "AI mahsulot yaratish: No-code + AI (Bubble, Glide)"),
    (10, "AI etikasi, xavfsizligi va kelajagi"),
    (11, "AI startap g'oyasi + MVP taqdimoti"),
    (12, "Yakuniy AI audit va Hakathon"),
]

FE_DARSLAR = [
    (1,   "Kompyuterning fizik tuzilishi"),
    (2,   "Kompyuter ishlash tamoyillari"),
    (3,   "Operatsion tizimlar"),
    (4,   "Internet va uning ishlashi"),
    (5,   "Brauzerlar va ularning ishlashi"),
    (6,   "HTML kirish va asosiy tushunchalar"),
    (7,   "HTML teglari va atributlar"),
    (8,   "HTML5 semantik elementlar"),
    (9,   "HTML formalar"),
    (10,  "HTML jadvallar"),
    (11,  "HTML multimedia: rasm, audio, video"),
    (12,  "HTML meta teglar va SEO asoslari"),
    (13,  "CSS kirish va asosiy xususiyatlar"),
    (14,  "CSS selektorlar"),
    (15,  "CSS box model"),
    (16,  "CSS display va positioning"),
    (17,  "CSS Flexbox"),
    (18,  "CSS Grid"),
    (19,  "CSS ranglar va gradientlar"),
    (20,  "CSS animatsiyalar va tranzitsiyalar"),
    (21,  "CSS Pseudo-klasslar va Pseudo-elementlar"),
    (22,  "CSS o'zgaruvchilar (Custom Properties)"),
    (23,  "Responsive dizayn va Media Queries"),
    (24,  "CSS metodologiyalari: BEM, SMACSS"),
    (25,  "Bootstrap kirish va grid tizimi"),
    (26,  "Bootstrap komponentlar"),
    (27,  "Bootstrap formalar va modal oynalar"),
    (28,  "Bootstrap kengaytirilgan komponentlar"),
    (29,  "SASS/SCSS kirish"),
    (30,  "SASS: o'zgaruvchilar, mixin, extend"),
    (31,  "SASS: nesting, funksiyalar, operatorlar"),
    (32,  "JavaScript kirish va asosiy tushunchalar"),
    (33,  "JS: o'zgaruvchilar va ma'lumot turlari"),
    (34,  "JS: operatorlar va ifodalar"),
    (35,  "JS: shartli operatorlar"),
    (36,  "JS: tsikllar"),
    (37,  "JS: funksiyalar"),
    (38,  "JS: massivlar"),
    (39,  "JS: obyektlar"),
    (40,  "JS: DOM kirish"),
    (41,  "JS: DOM elementlari bilan ishlash"),
    (42,  "JS: hodisalar (Events)"),
    (43,  "JS: forma validatsiyasi"),
    (44,  "JS: ES6+ yangi imkoniyatlar (let/const, arrow fn)"),
    (45,  "JS: Destructuring va Spread/Rest"),
    (46,  "JS: Template literals va Optional chaining"),
    (47,  "JS: Modullar (import/export)"),
    (48,  "JS: Promises va asenkron dasturlash"),
    (49,  "JS: Async/Await"),
    (50,  "JS: Fetch API va AJAX"),
    (51,  "JS: JSON bilan ishlash"),
    (52,  "JS: LocalStorage va SessionStorage"),
    (53,  "JS: Regular Expressions"),
    (54,  "JS: Xatolarni ushlash (try/catch)"),
    (55,  "JS: Klass va OOP asoslari"),
    (56,  "JS: Prototip va meros"),
    (57,  "JS: Iterator va Generator"),
    (58,  "JS: Map, Set, WeakMap, WeakSet"),
    (59,  "JS: Closures va Scope"),
    (60,  "JS: Callback funksiyalar"),
    (61,  "JS: Higher-order funksiyalar"),
    (62,  "JS: Array metodlari (map, filter, reduce)"),
    (63,  "JS: String metodlari"),
    (64,  "JS: Date va Time bilan ishlash"),
    (65,  "JS: Math obyekti"),
    (66,  "JS: Brauzer API-lari (Geolocation, Notification)"),
    (67,  "JS: Canvas API"),
    (68,  "JS: Web Workers"),
    (69,  "JS: Service Workers va PWA kirish"),
    (70,  "Git kirish va asosiy buyruqlar"),
    (71,  "Git: branching va merging"),
    (72,  "GitHub va hamkorlikda ishlash"),
    (73,  "npm va Node.js kirish"),
    (74,  "Webpack va build vositalar"),
    (75,  "Vite kirish va konfiguratsiya"),
    (76,  "ESLint va Prettier"),
    (77,  "React kirish va JSX"),
    (78,  "React: komponentlar va props"),
    (79,  "React: state va useState"),
    (80,  "React: useEffect"),
    (81,  "React: hodisalarni boshqarish"),
    (82,  "React: shartli render va ro'yxatlar"),
    (83,  "React: formalar bilan ishlash"),
    (84,  "React: komponent turlari (class vs functional)"),
    (85,  "React: kontekst (Context API)"),
    (86,  "React: useReducer"),
    (87,  "React: Custom Hooks"),
    (88,  "React: useRef va useCallback"),
    (89,  "React: useMemo va performance optimization"),
    (90,  "React Router: navigatsiya asoslari"),
    (91,  "React Router: dinamik yo'llar va parametrlar"),
    (92,  "React Router: himoyalangan yo'llar"),
    (93,  "Redux Toolkit kirish"),
    (94,  "Redux: actions va reducers"),
    (95,  "Redux: thunk va asinxron amallar"),
    (96,  "React Query (TanStack Query) kirish"),
    (97,  "React Query: mutations va invalidation"),
    (98,  "Tailwind CSS kirish va utility-first konsepti"),
    (99,  "Tailwind CSS: responsive dizayn"),
    (100, "Tailwind CSS: animatsiya va tranzitsiyalar"),
    (101, "Material UI (MUI) kirish"),
    (102, "MUI: komponentlar va tema"),
    (103, "Ant Design kirish va komponentlar"),
    (104, "Formik va forma boshqaruvi"),
    (105, "React Hook Form"),
    (106, "Yup bilan forma validatsiyasi"),
    (107, "REST API bilan ishlash (Axios)"),
    (108, "GraphQL asoslari"),
    (109, "Apollo Client va React"),
    (110, "Authentication: JWT asoslari"),
    (111, "Authentication: login/logout oqimi"),
    (112, "Rol asosida ruxsat (RBAC)"),
    (113, "TypeScript kirish va asosiy turlar"),
    (114, "TypeScript: interfeys va tip aliasi"),
    (115, "TypeScript: generics"),
    (116, "TypeScript React bilan ishlash"),
    (117, "Testing kirish: Jest asoslari"),
    (118, "React Testing Library"),
    (119, "E2E testing: Cypress kirish"),
    (120, "Accessibility (a11y) asoslari"),
    (121, "Web Performance optimallashtirish"),
    (122, "SEO va meta teglar"),
    (123, "Progressive Web Apps (PWA)"),
    (124, "Next.js kirish va SSR/SSG"),
    (125, "Next.js: routing va sahifalar"),
    (126, "Next.js: API Routes"),
    (127, "Next.js: Image va Font optimallashtirish"),
    (128, "Next.js: App Router va Server Components"),
    (129, "Next.js: data fetching strategiyalari"),
    (130, "Deployment: Vercel va Netlify"),
    (131, "CI/CD asoslari: GitHub Actions"),
    (132, "Docker kirish frontend uchun"),
    (133, "Micro-frontends arxitekturasi"),
    (134, "Monorepo: Nx va Turborepo"),
    (135, "Web Components va Custom Elements"),
    (136, "Svelte kirish"),
    (137, "Vue.js kirish va asosiy konseptlar"),
    (138, "Angular kirish"),
    (139, "Storybook: UI komponent dokumentatsiyasi"),
    (140, "Design Systems yaratish"),
    (141, "Figma va dizayn handoff"),
    (142, "Animatsiya kutubxonalari: Framer Motion"),
    (143, "Three.js va 3D Web"),
    (144, "WebSocket va real-time ilovalar"),
    (145, "WebAssembly kirish"),
    (146, "Browser DevTools: debugging va profiling"),
    (147, "Code Review madaniyati va best practices"),
    (148, "Clean Code va SOLID tamoyillari"),
    (149, "Design Patterns frontend uchun"),
    (150, "Monolith vs Microservices frontend nuqtai nazaridan"),
    (151, "Portfolio sayt yaratish: reja va arxitektura"),
    (152, "Portfolio sayt: dizayn va responsive layout"),
    (153, "Portfolio sayt: React bilan yaratish"),
    (154, "Portfolio sayt: animatsiyalar va final polish"),
    (155, "Yakun loyihasi: texnik topshiriq va reja"),
    (156, "Grand Yakun: Yakuniy loyihalar himoyasi"),
]


class Command(BaseCommand):
    help = "IT, AI va Frontend dastur darslarini bazaga yuklaydi"

    def handle(self, *args, **options):
        from schedule.models import Dastur

        yaratildi = 0
        yangilandi = 0

        for fan, darslar in [('IT', IT_DARSLAR), ('AI', AI_DARSLAR), ('FE', FE_DARSLAR)]:
            for raqam, sarlavha in darslar:
                obj, created = Dastur.objects.update_or_create(
                    fan=fan,
                    dars_raqami=raqam,
                    defaults={'sarlavha': sarlavha},
                )
                if created:
                    yaratildi += 1
                else:
                    yangilandi += 1

        self.stdout.write(self.style.SUCCESS(
            f"Tayyor: {yaratildi} ta yangi dars qo'shildi, {yangilandi} ta yangilandi."
        ))
