from django.core.management.base import BaseCommand

IT_DARSLAR = [
    (1,  "Kursga kirish + Startap tafakkuri + Ish tizimi"),
    (2,  "Kompyuter arxitekturasi: CPU, RAM, HDD/SSD"),
    (3,  "Operatsion tizimlar: Windows, Linux, macOS"),
    (4,  "Internet va tarmoqlar: IP, DNS, HTTP, HTTPS"),
    (5,  "Dasturlash asoslari: Python bilan tanishuv"),
    (6,  "Ma'lumotlar turlari, o'zgaruvchilar, shartlar"),
    (7,  "Tsikllar, funksiyalar, modullar"),
    (8,  "Fayl bilan ishlash, kutubxonalar"),
    (9,  "OOP: Klasslar, obyektlar, meros"),
    (10, "Ma'lumotlar bazasi: SQL asoslari"),
    (11, "SQLite va Python bilan DB ishlash"),
    (12, "Web asoslari: HTML, CSS, JavaScript kirish"),
    (13, "API nima? REST API bilan ishlash"),
    (14, "Git va GitHub: versiya boshqaruvi"),
    (15, "Linux terminal buyruqlari va bash skriptlar"),
    (16, "Kiberxavfsizlik asoslari: shifrlash, xujumlar"),
    (17, "Bulut texnologiyalari: AWS, GCP, Azure"),
    (18, "Docker va konteynerlashtirish"),
    (19, "Loyiha boshqaruvi: Agile, Scrum, Trello"),
    (20, "Prezentatsiya va kommunikatsiya ko'nikmalari"),
    (21, "Startap g'oyasi: BMC (Business Model Canvas)"),
    (22, "MVP yaratish va testlash"),
    (23, "Pitch deck tayyorlash va taqdimot"),
    (24, "FINAL — Portfolio + MVP + Startap himoya"),
]

AI_DARSLAR = [
    (1,  "AI umuman nima? Tarix, turlari, hozirgi holat"),
    (2,  "ChatGPT va prompt engineering asoslari"),
    (3,  "Prompt muhandisligi: advanced texnikalar (CoT, Few-shot, Role)"),
    (4,  "AI vositalar: Midjourney, DALL·E, Runway, Sora"),
    (5,  "AI yordamida biznes avtomatlashtirish: Zapier, Make.com"),
    (6,  "AI agentlar: AutoGPT, LangChain, CrewAI"),
    (7,  "Ma'lumot tahlili uchun AI: ChatGPT + Excel/Sheets"),
    (8,  "AI bilan kontent yaratish: blog, video, SMM"),
    (9,  "AI mahsulot yaratish: No-code + AI (Bubble, Glide)"),
    (10, "AI etikasi, xavfsizligi va kelajagi"),
    (11, "AI startap g'oyasi + MVP taqdimoti"),
    (12, "Yakuniy AI audit va Hakathon"),
]

FE_DARSLAR = [
    (1,   "Kompyuterning fizik tuzilishi (Hardware). Operatsion tizimlar (OS) arxitekturasi va fayllar tizimi bilan ishlash."),
    (2,   "Linux va Windows terminali (CLI) asoslari. Eng muhim buyruqlar (cd, ls, mkdir, pwd) bilan ishlash."),
    (3,   "Internet qanday ishlaydi? Brauzer va Server modeli. URL manzil strukturasi, DNS va HTTP/HTTPS protokollari mohiyati."),
    (4,   "VS Code dasturini o'rnatish va uning interfeysi. Loyihalar jildini to'g'ri shakllantirish qoidalari."),
    (5,   "Front-End dasturchi uchun eng muhim VS Code kengaytmalari (Extensions) va ichki sozlamalarni (Settings.json) sozlash."),
    (6,   "Markdown tili sintaksisi va qoidalari. Loyihalar uchun professional README.md faylini yozish standarti."),
    (7,   "HTML tarixi va uning hujjatchilik strukturasi (html, head, body). Element va Atribut tushunchalari."),
    (8,   "Matnli elementlar bilan ishlash: Sarlavhalar (h1-h6), abzaslar (p),urg'u beruvchi teglari (strong, em, br, hr)."),
    (9,   "Ro'yxatlar yaratish (ul, ol, li). Giperhavolalar (a) va ularning atributlari (href, target). Rasmlarni responsive joylash (img, picture, srcset)."),
    (10,  "HTML jadvallari: Murakkab jadvallarni shakllantirish (table, tr, td, th, thead, tbody, colspan, rowspan)."),
    (11,  "HTML5 Semantik teglari: Sahifa arxitekturasini to'g'ri qurish (header, nav, main, section, article, aside, footer)."),
    (12,  "W3C HTML Validatsiyasi bilan ishlash. Saytlarni qidiruv tizimlariga (SEO) tayyorlashning dastlabki qoidalari."),
    (13,  "CSS nima? CSS-ni HTML sahifaga ulashning 3 xil usuli (Inline, Internal, External). Selektorlar turlari."),
    (14,  "Ranglar bilan ishlash (HEX, RGB, HSL). Fon (Background) xususiyatlari va mukammal matn (Typography) stillari."),
    (15,  "CSS Box Model (Blok modeli): margin, border, padding va content o'rtasidagi o'zaro farq va hisob-kitoblar."),
    (16,  "Elementlarning ko'rinish turlari: display: block, inline, inline-block va none xususiyatlari."),
    (17,  "Elementlarni joylashtirish (CSS Positioning): static, relative, absolute xususiyatlarining zanjirli ishlashi."),
    (18,  "Murakkab joylashuvlar: position: fixed va sticky. Qavatlar iyerarxiyasi (z-index) va element sig'may qolgandagi holat (overflow)."),
    (19,  "Flexbox asoslari: Konteyner xususiyatlari (display: flex, flex-direction, flex-wrap, justify-content, align-items)."),
    (20,  "Flexbox elementlari xususiyatlari: Elementlar o'lchami va ketma-ketligi (order, flex-grow, flex-shrink, flex-basis)."),
    (21,  "Grid Layout tizimiga kirish: To'rli karkas yaratish (display: grid, grid-template-columns, grid-template-rows, gap). Grid Area va chiziqlarga asoslangan joylashuvlar."),
    (22,  "Responsive dizayn falsafasi. Viewport tushunchasi. Media Queries (@media) yozish qoidalari."),
    (23,  "Mobile-first va Desktop-first strategiyalari asosida moslashuvchan maketlar yaratish amaliyoti."),
    (24,  "Jami o'tilgan HTML va CSS mavzulari asosida to'liq responsive Shaxsiy Portfolio sahifasini noldan yig'ish."),
    (25,  "Versiyalar boshqaruvi tizimi. Kompyuterga Git o'rnatish va global sozlamalar (git config). git init va git status."),
    (26,  "Loyiha versiyalarini saqlash: git add, git commit -m va git log buyruqlari. Loyihada .gitignore faylidan to'g'ri foydalanish."),
    (27,  "GitHub platformasi. Masofaviy repozitoriyalar bilan ishlash: git remote add, git push, git pull va git clone."),
    (28,  "Git Branching (Shoxlanish): Yangi funksiyalar uchun tarmoqlar ochish (git branch, git checkout / git switch, git merge)."),
    (29,  "Jamoaviy ishlashdagi eng katta muammo: Git Merge Conflict (mojarolar) va ularni VS Code ichida to'g'ri bartaraf etish."),
    (30,  "Fork qilish, Jamoaga kodni tekshirish uchun taqdim etish (Pull Request — PR) va Open Source loyihalarga hissa qo'shish madaniyati."),
    (31,  "Tailwind CSS falsafasi va utility-first tushunchasi. Node.js muhiti orqali Tailwind-ni loyihaga o'rnatish va tailwind.config.js sozlamalari."),
    (32,  "Tailwind-da Layout, Typography, Spacing (Padding/Margin) va Sizing klasslari yordamida tezkor interfeys qurish."),
    (33,  "Tailwind yordamida Flexbox va Grid tizimlarini boshqarish. Ranglar va maxsus birlar bilan ishlash."),
    (34,  "Tailwind-da responsive ekranlar (sm, md, lg, xl) va Dark Mode tizimini klasslar yordamida bir zumda sozlash."),
    (35,  "Elementlarning holatlari bilan ishlash: hover:, focus:, active: va pseudo-klasslarni Tailwind tilida yozish."),
    (36,  "Tailwind imkoniyatlaridan foydalanib, to'liq va zamonaviy bitta Landing Page sahifasini yig'ish va uni GitHub-ga yuklash."),
    (37,  "JavaScript nima? Skriptlarni ulash usullari. Brauzer konsoli bilan ishlash (console.log)."),
    (38,  "O'zgaruvchilar dunyosi: let va const o'rtasidagi farqlar (eski var muammosi). Ma'lumot turlari (Primitive vs Reference)."),
    (39,  "Operatorlar: Arifmetik, Tayinlov (Assignment), Solishtirish (Comparison) va Mantiqiy (&&, ||, !) operatorlar."),
    (40,  "Shartli mantiqiy operatorlar: if, else if, else. Switch va Ternary (uchlik) operatorlari bilan ishlash."),
    (41,  "Sikllar (Loops) — 1-qism: for sikli, unda break va continue buyruqlarining qo'llanilishi."),
    (42,  "Sikllar — 2-qism: while va do while sikllari. Obyekt va massivlarni aylanish uchun for...in va for...of sikllari."),
    (43,  "String (Matn) metodlari: slice, replace, toUpperCase, toLowerCase, includes, Template Literals."),
    (44,  "Number (Sonlar) metodlari va Math obyektining imkoniyatlari (Math.round, floor, ceil, random). Sonlarni tiplarga o'tkazish."),
    (45,  "JavaScript-da vaqt bilan ishlash: Date obyekti, metodlari, real vaqtni va sanani formatlash."),
    (46,  "Funksiyalar (Functions): Function Declaration va Function Expression tushunchalari hamda ularning farqlari."),
    (47,  "Zamonaviy Arrow Functions (O'qsimon funksiyalar). Funksiyalarda parametrlar, Argumentlar va return qiymati. Default parametrlar."),
    (48,  "JavaScript Call Stack va xotira boshqaruvi: Global Scope, Function Scope va Block Scope. Hoisting (Ko'tarilish) mexanizmi."),
    (49,  "Array (Massiv) asoslari: Element qo'shish va o'chirish metodlari (push, pop, shift, unshift, splice, slice, concat)."),
    (50,  "Massiv iteratsiyasi (Higher-Order Array Methods): forEach va elementlarni transformatsiya qiluvchi map hamda saralovchi filter metodlari."),
    (51,  "Massivlarni chuqur qayta ishlash: reduce, find, some, every metodlari amaliy misollarda."),
    (52,  "Object (Obyekt) asoslari: Obyekt yaratish, uning xususiyatlariga kirish (dot va bracket notation). Property shorthand qulayligi."),
    (53,  "Obyektlarning o'rnatilgan global metodlari: Object.keys(), Object.values(), Object.entries() va obyektlarni nusxalash (Object.assign())."),
    (54,  "Destructuring (Strukturasizlantirish): Massiv va obyektlardan ma'lumotlarni oson ajratib olish. ES6 Spread va Rest operatorlari."),
    (55,  "Callback functions (Ortga qaytuvchi funksiyalar) arxitekturasi va mantiqiy ishlash zanjiri."),
    (56,  "Higher-Order functions (Yuqori tartibli funksiyalar) arxitekturasini noldan o'zimiz yozib ko'rish amaliyoti."),
    (57,  "Dasturlashda 'Clean Code' (Toza kod) prinsiplari. JavaScript-da funksiyalarni to'g'ri nomlash va optimal arxitektura qilish."),
    (58,  "Error Handling (Xatoliklar bilan ishlash): Kod sinishining oldini olish (try, catch, finally, throw new Error)."),
    (59,  "Debugging (Kod xatolarini qidirish) san'ati. Brauzer ichidagi debugger instrumenti va Breakpoints bilan ishlash."),
    (60,  "JavaScript-ning qat'iy rejimi: 'use strict' nima va u kod yozish madaniyatiga qanday ta'sir qiladi?"),
    (61,  "Obyektga Yo'naltirilgan Dasturlash (OOP) asoslari. JavaScript-da klasslar (class) va obyektdan nusxa oluvchi constructor funksiyasi."),
    (62,  "Klasslarda metodlar yaratish. Klasslarning vorisligi (extends) va ota klass xususiyatlarini chaqirish (super)."),
    (63,  "Klasslarda xavfsizlik va inkapsulyatsiya elementlari: Static methods, Getter va Setter funksiyalari bilan ishlash."),
    (64,  "JavaScript Modul tizimi (ES Modules): Kodni qismlarga bo'lish (import va export turlari)."),
    (65,  "Brauzer xotirasi bilan ishlash: localStorage va sessionStorage obyektlari, ma'lumotlarni xotiraga yozish va o'qish."),
    (66,  "localStorage xotirasidan foydalanadigan mukammal va ma'lumotlari saqlanib qoladigan JS Kalkulyator/Xarajatlar o'lchagichi dasturini yozish."),
    (67,  "Brauzer muhiti: BOM va DOM Tree tushunchasi. HTML elementlarini JS-da tutib olish (querySelector, querySelectorAll)."),
    (68,  "DOM elementlarini manipulyatsiya qilish: Element ichidagi matn va kodni o'zgartirish, atributlarni boshqarish (setAttribute)."),
    (69,  "Dinamik DOM elementlari: Kod yordamida yangi element yaratish (createElement) va qo'shish (appendChild, remove)."),
    (70,  "Hodisalar (Events) bilan ishlash. Elementlarga quloq solish (addEventListener). Hodisalar (click, input, submit)."),
    (71,  "Hodisa obyekti imkoniyatlari. Standart amallarni to'xtatish (e.preventDefault()), tarqalishni cheklash (e.stopPropagation())."),
    (72,  "Hodisalar delegatsiyasi (Event Delegation) arxitekturasi yordamida dinamik yaratilgan elementlar hodisalarini boshqarish."),
    (73,  "JavaScript orqali murakkab HTML formalari bilan ishlash. Foydalanuvchi ma'lumotlarini real vaqtda tekshirish (Validation)."),
    (74,  "DOM-da klasslar bilan manipulyatsiya: Elementlarga CSS klasslarini qo'shish va olib tashlash (classList.toggle)."),
    (75,  "HTML, CSS (Tailwind) va DOM manipulyatsiyasi yordamida to'liq interaktiv dastur interfeysini qurish amaliyoti."),
    (76,  "Ma'lumotlar almashinuvi formati: JSON nima? JSON.stringify va JSON.parse metodlari."),
    (77,  "Loyihada ma'lumotlarni qo'shish (Create), o'qish (Read), yangilash (Update) va o'chirish (Delete) — CRUD tizimi."),
    (78,  "To'liq dinamik, qidiruv tizimiga ega va xotiradan o'chib ketmaydigan Task Manager (Todo-List) professional ilovasini ishlab chiqish."),
    (79,  "Asinxron JS asoslari. Sinxron va Asinxron kod farqi. Event Loop va Web APIs ishlash prinsipi."),
    (80,  "Va'dalar dunyosi: Promise arxitekturasi hamda .then(), .catch(), .finally() zanjirlari."),
    (81,  "Fetch API va HTTP so'rovlar. Serverdan ma'lumotlarni olish (GET). Zamonaviy Async/Await sintaksisi."),
    (82,  "Serverga ma'lumot yuborish va o'zgartirish: Fetch API orqali POST, PUT va DELETE so'rovlarini bajarish."),
    (83,  "Tarmoq xatoliklarini ushlash. Ma'lumot kelayotgan jarayonda UI indikatorlarini (Loading state) ko'rsatish."),
    (84,  "Jonli ob-havo ma'lumotlarini taqdim etuvchi hamda dynamic fon o'zgaruvchi Weather App (OpenWeatherMap API) loyihasini yakunlash."),
    (85,  "TypeScript nima va uning afzalliklari (Static Typing). Global o'rnatish, tsc va tsconfig.json fayli."),
    (86,  "Type Annotations: string, number, boolean, any, unknown va void tiplari bilan ishlash."),
    (87,  "TypeScript-da to'plamlar: Massivlarni tiplashtirish (Array), qat'iy massivlar (Tuple) va Enum."),
    (88,  "Murakkab tiplar: Obyektlarni tiplashtirish. interface va type alias tushunchalari, farqlari."),
    (89,  "Tiplar kombinatsiyasi: Union Types, tiplarni birlashtirish (Intersection Types) va aniq qiymatli Literal Types."),
    (90,  "Funksiyalarni qat'iy tiplashtirish. Ixtiyoriy (optional) va standart (default) parametrlar."),
    (91,  "TypeScript-da dinamik tiplar: Generics (Umumlashtirilgan tiplar) tushunchasi va funksiyalarda qo'llanishi."),
    (92,  "Interfeyslar va Klasslarda Generics tushunchasini qo'llash amaliyoti (Generic Interfaces & Classes)."),
    (93,  "TypeScript Utility Types: Partial, Pick, Omit, Readonly tiplari yordamida kodni optimallash."),
    (94,  "Type Narrowing (Tiplarni toraytirish): typeof, instanceof va in operatorlari bilan ishlash xavfsizligi."),
    (95,  "Tiplarni majburlash: Type Assertion (as kalit so'zi) hamda ! (Non-null Assertion) operatori."),
    (96,  "Oldingi modullarda sof JavaScript-da yozilgan murakkabroq dynamic loyihani to'liq TypeScript-ga o'tkazish (Refactoring)."),
    (97,  "SPA tushunchasi. React kutubxonasi falsafasi. Tezkor Vite asbobida loyiha ochish va papkalar strukturasi."),
    (98,  "TSX (TypeScript XML) asoslari: JSX qoidalari, expressionlar, atributlar va JSX ichida mantiqiy amallar."),
    (99,  "React Komponentlari: Funksional komponentlar yaratish va ularni eksport/import qilish madaniyati."),
    (100, "Props (Xususiyatlar) tushunchasi: Ma'lumot uzatish. TypeScript-da Props uchun type va interface yozish."),
    (101, "Maxsus children propidan foydalanish (Wrapper komponentlar). Props-ga standart qiymatlar berish."),
    (102, "Conditional Rendering (Shartli render) hamda massiv elementlarini dynamic komponent qilib chiqarish, key atributi."),
    (103, "React-da holat boshqaruvi. useState hooki bilan ishlash va UI yangilanish mexanizmi."),
    (104, "useState hookida murakkab tiplar (Massiv/Obyekt) bilan TS muhitida immutable (o'zgarmas) ishlash qoidalari."),
    (105, "React Event Handling. TypeScript muhitida hodisalar (Form event, Mouse event) tiplarini to'g'ri belgilash."),
    (106, "Yon ta'sirlar bilan ishlash: useEffect hookiga kirish. Mount, Update va Unmount hayotiy bosqichlari."),
    (107, "useEffect dependency array bilan ishlash. Nojo'ya oqibatlarni tozalash (Cleanup function) mexanizmi."),
    (108, "React-da asinxron operatsiyalar: useEffect ichida Fetch yoki Axios yordamida tashqi API-dan ma'lumot yuklash."),
    (109, "Formalar boshqaruvi: Controlled komponentlar yaratish. useState orqali input qiymatlarini ushlash."),
    (110, "Uncontrolled komponentlar va uning foydasi. DOM-ga ulanish uchun useRef hooki."),
    (111, "Unumdorlik: ID-lar yaratish uchun useId hooki. Input elementlariga avtomatik fokus berish amaliyoti."),
    (112, "Komponentlarning keraksiz qayta render bo'lish muammosi. React.memo orqali keshga olish."),
    (113, "Og'ir hisob-kitoblarni keshlovchi useMemo hooki va uning amaliy ahamiyati."),
    (114, "Funksiyalarni qayta yaratilishdan himoya qiluvchi va xotirani tejovchi useCallback hooki."),
    (115, "Custom Hooks (Shaxsiy hooklar): Kod takrorlanishining oldini olish falsafasi va yaratish qoidalari."),
    (116, "Tashqi API bilan ishlovchi mukammal, universal va tiplashtirilgan useFetch custom hookini yozish."),
    (117, "Brauzer xotirasi bilan chiroyli ishlovchi va avtomatlashtirilgan useLocalStorage shaxsiy hookini yaratish."),
    (118, "Prop Drilling muammosi va Global State. React Context API arxitekturasi: createContext va useContext."),
    (119, "Context API-ni TypeScript bilan xavfsiz integratsiya qilish va Global Provider-lar yozish."),
    (120, "Context API yordamida global Dark/Light Mode tizimini yoki foydalanuvchi tizimga kirganlik (Mock Auth) holatini boshqarish."),
    (121, "React Router (v6+) kutubxonasi. Sahifalar navigatsiyasini sozlash: BrowserRouter, Routes, Route."),
    (122, "Navigatsiya elementlarini moslashtirish (NavLink). Dasturiy ko'chishlar (useNavigate) va 404 sahifasi."),
    (123, "Dinamik marshrutlar bilan ishlash: Parametrlarni tutish (useParams) va /products/:id sahifasini qurish."),
    (124, "Professional formalar: react-hook-form kutubxonasi o'rnatish va integratsiya qilish."),
    (125, "Formalarni tiplashtirilgan sxemalar orqali validatsiya qilish: zod kutubxonasi va uni ulash."),
    (126, "Vite + TS + Context API + Router + Tailwind asosida to'liq va ma'lumotlari saqlanuvchi Savat (E-commerce Basket) tizimi loyihasi."),
    (127, "Next.js nima? React va Next.js-ning farqlari va uning Front-End'da ustunligi. Zamonaviy App Router loyihasini ochish."),
    (128, "Jildlar iyerarxiyasiga asoslangan marshrutlash (File-system Routing). page.tsx va layout.tsx fayllari."),
    (129, "Ichma-ich joylashgan (Nested) Layoutlar yaratish. Global umumiy qismlarni (Navbar/Footer) to'g'ri taqsimlash."),
    (130, "Next.js navigatsiya tizimi: Optimallashgan Link komponenti va dasturiy boshqarish uchun useRouter hooki."),
    (131, "Dinamik yo'laklar ([id]) va barcha yo'laklarni tutuvchi dinamik routerlar ([...slug]) yordamida arxitektura qurish."),
    (132, "Tailwind CSS-ni Next.js loyihasi bilan chuqur integratsiya qilish va global karkas stillarini shakllantirish."),
    (133, "Server Components va Client Components farqlari hamda ularni to'g'ri joyda qo'llash strategiyasi ('use client')."),
    (134, "Server Components ichida to'g'ridan-to'g'ri async/await orqali data fetching (Ma'lumot olish) qilish."),
    (135, "Next.js Caching va Revalidation: Server ma'lumotlarini keshda saqlash va ma'lum vaqt oralig'ida avtomatik yangilash (ISR)."),
    (136, "Next.js-da ichki API yaratish: Route Handlers arxitekturasi (route.ts). Unda GET va POST so'rovlari."),
    (137, "API Routes ichida PUT va DELETE so'rovlarini qayta ishlash. Status Codes bilan to'g'ri ishlash."),
    (138, "Next.js Middleware tushunchasi: Foydalanuvchi sahifaga kirmasidan oldin uning huquqlarini tekshirish (Protected Routes)."),
    (139, "Qidiruv optimizatsiyasi (SEO): Next.js Metadata API bilan ishlash. Dinamik va statik metadatani boshqarish."),
    (140, "Rasmlarni avtomatik siquvchi va WebP formatga o'tkazuvchi next/image komponenti imkoniyatlari."),
    (141, "Google shriftlarini xavfsiz yuklovchi next/font hamda tashqi skriptlar uchun next/script."),
    (142, "Next.js Rendering Turlari: Static Rendering (SSG) va Dynamic Rendering (SSR) tizimlarining farqlari."),
    (143, "Loyihani ishlab chiqarishga (Production build) tayyorlash, muhit o'zgaruvchilari (.env) xavfsizligi."),
    (144, "Next.js va Tailwind CSS yordamida yaratilgan, to'liq SEO optimallashgan va Vercel'ga deploy qilingan Full-stack Yangiliklar/Blog sayti."),
    (145, "Sanoat standarti: Shadcn/UI nima va nega u odatiy kutubxonalardan ustun? Radix UI va Tailwind integratsiyasi."),
    (146, "Shadcn/UI CLI orqali tayyor komponentlarni (Button, Card, Dialog/Modal) loyihaga chaqirish va o'zgartirish."),
    (147, "Murakkab komponentlar: Shadcn/UI Form, Dropdown Menu va Toast indikatorlarini Next.js formalariga ulash."),
    (148, "Firebase platformasi. Loyiha ochish va Next.js-ga Firebase SDK ulanishi. Firebase Auth (Tizimga kirish)."),
    (149, "Google Firestore real-time NoSQL ma'lumotlar bazasi bilan connectsiyani yo'lga qo'yish. Ma'lumot yozish va olish."),
    (150, "Next.js + Tailwind + Shadcn/UI + Firebase kombinatsiyasida to'liq ishlovchi loyihani Vercel'ga yuklash."),
    (151, "Real bozor talabiga javob beruvchi Grand Loyiha (SaaS platforma, CRM tizimi yoki murakkab E-commerce) g'oyasi va talablari (SRS)."),
    (152, "Jamoaviy loyihalarni boshqarish metodologiyasi (Agile/Scrum). GitHub Projects taxtalarida vazifalarni (tasks) taqsimlash."),
    (153, "Git Branching strategiyasi (GitFlow): main, develop va yangi funksiyalar (feature) tarmoqlari bilan ishlash amaliyoti."),
    (154, "Grand Loyihaning yakuniy test jarayonlari (Bug fixing) va uni Vercel platformasiga yakuniy xavfsiz joylash (Production Deploy)."),
    (155, "GitHub profilini (Readme) bezatish, LinkedIn profilini optimizatsiyalash va HR standartlari bo'yicha professional Rezyume (CV) shakllantirish."),
    (156, "Grand Yakun: Yakuniy loyihalar himoyasi (Presentation), guruh oldida 'Demo' taqdimot qilish va mentorlar tomonidan Professional Code Review."),
]


class Command(BaseCommand):
    help = "IT, AI va Frontend dastur darslarini bazaga yuklaydi"

    def handle(self, *args, **options):
        from schedule.models import Dastur

        yaratildi = 0
        yangilandi = 0

        for fan, darslar in [('IT', IT_DARSLAR), ('AI', AI_DARSLAR), ('FE', FE_DARSLAR)]:
            for raqam, sarlavha in darslar:
                obj, created = Dastur.objects.update_or_create(
                    fan=fan,
                    dars_raqami=raqam,
                    defaults={'sarlavha': sarlavha},
                )
                if created:
                    yaratildi += 1
                else:
                    yangilandi += 1

        self.stdout.write(self.style.SUCCESS(
            f"Tayyor: {yaratildi} ta yangi dars qo'shildi, {yangilandi} ta yangilandi."
        ))
