# Generated by Django 6.0.6 on 2026-06-26 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=200)),
                ('telegram_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('telefon', models.CharField(blank=True, max_length=20, null=True)),
                ('mutaxassislik', models.CharField(blank=True, max_length=100, null=True)),
                ('yaratilgan_sana', models.DateTimeField(auto_now_add=True)),
                ('yangilangan_sana', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['ism'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hafta_kuni', models.CharField(choices=[('monday', 'Dushanba'), ('tuesday', 'Seshanba'), ('wednesday', 'Chorshanba'), ('thursday', 'Payshanba'), ('friday', 'Juma'), ('saturday', 'Shanba'), ('sunday', 'Yakshanba')], max_length=10)),
                ('boshlanish_vaqti', models.TimeField()),
                ('tugash_vaqti', models.TimeField()),
                ('dars_raqami', models.IntegerField()),
                ('fan_nomi', models.CharField(max_length=100)),
                ('mavzu', models.TextField()),
                ('xona', models.CharField(blank=True, max_length=20, null=True)),
                ('guruh', models.CharField(blank=True, max_length=50, null=True)),
                ('faol', models.BooleanField(default=True)),
                ('eslatma', models.TextField(blank=True, null=True)),
                ('yaratilgan_sana', models.DateTimeField(auto_now_add=True)),
                ('yangilangan_sana', models.DateTimeField(auto_now=True)),
                ('ustoz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='darslar', to='schedule.teacher')),
            ],
            options={
                'ordering': ['hafta_kuni', 'boshlanish_vaqti'],
                'unique_together': {('ustoz', 'hafta_kuni', 'dars_raqami')},
            },
        ),
    ]
