# Generated by Django 6.0.6 on 2026-06-26 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='lesson',
            name='hafta_turi',
            field=models.CharField(choices=[('har_doim', 'Har doim'), ('toq', 'Toq hafta (1, 3, 5...)'), ('juft', 'Juft hafta (2, 4, 6...)')], default='har_doim', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('ustoz', 'hafta_kuni', 'dars_raqami', 'hafta_turi')},
        ),
    ]
