# Generated by Django 6.0.6 on 2026-07-02 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_teacher_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('ustoz', 'hafta_kuni', 'dars_raqami', 'hafta_turi', 'guruh')},
        ),
    ]
