# Generated by Django 6.0.6 on 2026-07-02 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_alter_lesson_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotXabar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.IntegerField(blank=True, null=True)),
                ('chat_id', models.BigIntegerField()),
                ('jadval_sana', models.DateField()),
                ('haftalik', models.BooleanField(default=False)),
                ('qabul_qilindi', models.BooleanField(default=False)),
                ('yuborilgan_vaqt', models.DateTimeField(auto_now_add=True)),
                ('qabul_vaqti', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-yuborilgan_vaqt'],
            },
        ),
    ]
